### ISSUE TITLE
Update charts repo

### ISSUE THREAD

**Issue by brunopenha** [gemalto/miniapps#14]
Some charts are still point to Gemalto repo.

https://github.com/ThalesGroup/miniapps/blob/master/charts/mysql/Chart.yaml
https://github.com/ThalesGroup/miniapps/blob/master/charts/cassandra/Chart.yaml

IE:
helm install miniapps/cassandra --name cassandra --debug
[debug] Created tunnel using local port: '41419'

[debug] SERVER: "127.0.0.1:41419"

[debug] Original chart version: ""
Error: Failed to fetch https://gemalto.github.io/miniapps/cassandra-1.0.0+build.29.tgz : 404 Not Found

**Comment by cvila84** [comment]
- Fixed manually by https://github.com/ThalesGroup/miniapps/commit/4db94695b57e851ae8c78913cf9dddf350b7ca6c
- Travis CI is back and works : https://travis-ci.org/github/ThalesGroup/miniapps/builds/661054815
